name: Docker Image Fail2ban

on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/fail2ban-latest.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Compiling new node software
      run: |      
        docker build . --compress --tag redoracle/fail2ban
    - name: docker push
      run: |
        docker push redoracle/fail2ban
